openapi: 3.1.0
info:
  title: CycleDoc GPX Heatmap API
  version: "1.0"
  description: >
    Diese API verarbeitet GPX-Koordinaten und analysiert Risiken entlang einer Strecke.
    Sie erstellt eine farbige Heatmap mit optionalen Saniposten und liefert segmentweise Risikobewertung
    inkl. Wetter-, Strecken- und Oberflächendaten.

servers:
  - url: https://gpx-heatmap-api.onrender.com

paths:
  /heatmap-quick:
    post:
      summary: Risikoanalyse mit Heatmap-Visualisierung (SpeedBoost – 0.005 km Segmente)
      operationId: generateHeatmapQuick
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeatmapRequest'
      responses:
        '200':
          description: Analyseergebnis mit Heatmap-URL, Segmentdaten und Streckenlänge
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeatmapResponse'
        '400':
          description: Fehlerhafte oder fehlende Daten

components:
  schemas:
    HeatmapRequest:
      type: object
      required: [coordinates, fahrer_typ, alter, geschlecht]
      properties:
        coordinates:
          type: array
          items:
            type: array
            items:
              type: number
        fahrer_typ:
          type: string
          example: hobby
        anzahl:
          type: integer
          example: 5
        alter:
          type: integer
          example: 39
        geschlecht:
          type: string
          example: m
        massenstart:
          type: boolean
        overuse_knee:
          type: boolean
        rueckenschmerzen:
          type: boolean
        material:
          type: string
          example: aluminium
        rennen_art:
          type: string
          example: road
        start_time:
          type: string
          format: date-time
        wetter_override:
          type: object
          properties:
            temperature:
              type: number
              example: 12
            wind_speed:
              type: number
              example: 10
            precip:
              type: number
              example: 0.2
            condition:
              type: string
              example: cloudy
        schutzausruestung:
          type: object
          properties:
            helm:
              type: boolean
            protektoren:
              type: boolean

    HeatmapResponse:
      type: object
      properties:
        heatmap_url:
          type: string
          format: uri
          example: "https://gpx-heatmap-api.onrender.com/static/heatmap_YYYYMMDDHHMMSS.html"
        distance_km:
          type: number
          example: 15.0
        segments:
          type: array
          items:
            type: object
            properties:
              segment_index:
                type: integer
              center:
                type: object
                properties:
                  lat:
                    type: number
                  lon:
                    type: number
              slope:
                type: number
              sharp_curve:
                type: boolean
              terrain:
                type: string
              weather:
                type: object
                properties:
                  temperature:
                    type: number
                  wind_speed:
                    type: number
                  precip:
                    type: number
                  condition:
                    type: string
              street_surface:
                type: string
              nighttime:
                type: boolean
              risk:
                type: integer
              injuries:
                type: array
                items:
                  type: string
              sani_needed:
                type: boolean
