openapi: 3.0.0
info:
  title: CycleDoc GPX Heatmap API
  version: "1.0"
  description: |
    Diese API verarbeitet GPX-Daten und erstellt Risiko-Heatmaps auf Basis von Wetter, Streckenprofil und wissenschaftlicher Studienlage.
    Sie unterstützt das Parsen von GPX-Dateien, Segmentierung großer Strecken und die automatische Analyse via Wetterdaten oder manuelle Eingabe.

servers:
  - url: https://gpx-heatmap-api.onrender.com

paths:

  /parse-gpx:
    post:
      summary: GPX-Datei parsen (liefert auch Streckenlänge)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Extrahierte Koordinaten und Streckenlänge
          content:
            application/json:
              schema:
                type: object
                properties:
                  coordinates:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
                  distance_km:
                    type: number
                    description: Gesamtlänge der Strecke in Kilometern
        '400':
          description: Keine Datei empfangen

  /chunk-upload:
    post:
      summary: GPX-Koordinaten in Chunks speichern (serverseitig)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coordinates:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
                chunk_size:
                  type: integer
                  default: 200
      responses:
        '200':
          description: Anzahl der gespeicherten Chunks
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  chunks:
                    type: array
                    items:
                      type: string

  /heatmap-with-weather:
    post:
      summary: Risikoanalyse & Heatmap generieren (Standard)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeatmapRequest'
      responses:
        '200':
          description: Analyse mit Heatmap-Link und Risikosegmenten
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeatmapResponse'
        '400':
          description: Fehlerhafte oder fehlende Daten

  /heatmap-quick:
    post:
      summary: Präzise Risikoanalyse mit hoher Segmentdichte (SpeedBoost-Modus)
      description: >
        Funktioniert wie `/heatmap-with-weather`, nutzt aber eine deutlich feinere Segmentlänge (0.005 km).
        Liefert zusätzlich die gesamte Streckenlänge in Kilometern zurück.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeatmapRequest'
      responses:
        '200':
          description: Präzise Risikoanalyse mit zusätzlicher Streckenlänge (km)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeatmapResponseWithDistance'

components:
  schemas:

    HeatmapRequest:
      type: object
      properties:
        coordinates:
          type: array
          items:
            type: array
            items:
              type: number
        fahrer_typ:
          type: string
          example: hobby
        anzahl:
          type: integer
          example: 2
        alter:
          type: integer
        geschlecht:
          type: string
          example: mixed
        massenstart:
          type: boolean
        overuse_knee:
          type: boolean
        rueckenschmerzen:
          type: boolean
        material:
          type: string
          example: aluminium
        rennen_art:
          type: string
          example: road
        schutzausruestung:
          type: object
          properties:
            helm:
              type: boolean
            protektoren:
              type: boolean
        wetter_override:
          type: object
          properties:
            temperature:
              type: number
            wind_speed:
              type: number
            precip:
              type: number
            condition:
              type: string
        start_time:
          type: string
          format: date-time

    HeatmapResponse:
      type: object
      properties:
        heatmap_url:
          type: string
        segments:
          type: array
          items:
            $ref: '#/components/schemas/SegmentInfo'

    HeatmapResponseWithDistance:
      allOf:
        - $ref: '#/components/schemas/HeatmapResponse'
        - type: object
          properties:
            distance_km:
              type: number
              description: Gesamtlänge der Strecke

    SegmentInfo:
      type: object
      properties:
        segment_index:
          type: integer
        center:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
        slope:
          type: number
        sharp_curve:
          type: boolean
        terrain:
          type: string
        street_surface:
          type: string
        nighttime:
          type: boolean
        risk:
          type: integer
        injuries:
          type: array
          items:
            type: string
        sani_needed:
          type: boolean
        weather:
          type: object
          properties:
            temperature: { type: number }
            wind_speed: { type: number }
            precip: { type: number }
            condition: { type: string }
