openapi: 3.0.2
info:
  title: CycleDoc Heatmap-API
  description: |
    API for processing GPX data, segmenting routes, performing risk analysis, and generating interactive heatmaps.
    Calculates route length, assesses risks based on weather, slope, curves, and rider parameters, and provides a detailed report.
    Implements intelligent paramedic logic for critical segments.

    **Notes:**
    - Weather data requires `WEATHERSTACK_API_KEY` environment variable.
    - Logs are written to `app.log` for debugging (e.g., segment count, weather queries).
    - Rate limits: 10 requests/min per endpoint, 200/day, 50/hour globally.
    - Maximum 100,000 track points per request.

    Changelog: See [GitHub Releases](https://github.com/cycledoc/api/releases).
  version: 1.0.0
  contact:
    name: CycleDoc Support
    email: support@cycledoc.com
    url: https://cycledoc.com/support

servers:
  - url: https://gpx-heatmap-api.onrender.com
    description: Production server

tags:
  - name: Health
    description: Endpoints for checking API status.
  - name: Heatmap
    description: Endpoints for generating heatmaps and risk analyses.
  - name: GPX
    description: Endpoints for processing GPX files.
  - name: Utility
    description: Utility functions like chunking.

paths:
  /:
    get:
      tags: [Health]
      summary: Health-Check Endpoint
      description: Verifies API is running. Useful to confirm the API is operational before making other requests.
      operationId: healthCheck
      responses:
        '200':
          description: API is ready.
          content:
            text/plain:
              schema:
                type: string
                example: ✅ CycleDoc Heatmap-API ready

  /heatmap-quick:
    post:
      tags: [Heatmap]
      summary: Generate Heatmap and Detailed Report
      description: |
        Processes coordinates and parameters to create an interactive heatmap.
        Segments the route, analyzes risks (weather, slope, curves, rider profile), and generates a report.
        Weather data is fetched every 50 km along the route.
        Logs segment and risk details in `app.log`.
        Limited to 100,000 track points.
      operationId: generateHeatmapQuick
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - coordinates
                - start_time
              properties:
                coordinates:
                  type: array
                  items:
                    $ref: '#/components/schemas/Coordinate'
                  description: Array of [latitude, longitude, elevation?] coordinates.
                  example: [[48.137154, 11.576124, 520], [48.138, 11.577, 521], [48.139, 11.578, 522]]
                start_time:
                  type: string
                  format: date-time
                  description: Start time in ISO-8601 format (e.g., "2025-04-09T07:00:00Z"). UTC required (Z or +00:00). Naive datetimes assumed as UTC.
                  example: "2025-04-09T07:00:00Z"
                fahrer_typ:
                  type: string
                  enum: ["hobby", "c-lizenz", "anfänger", "a", "b", "elite", "profi"]
                  default: "hobby"
                  description: Rider type. Use 'profi' for professional riders to adjust risk assessment, 'hobby' for casual riders.
                  example: "hobby"
                anzahl:
                  type: integer
                  minimum: 1
                  default: 5
                  description: Number of riders. Higher numbers may increase risk in mass starts.
                  example: 5
                rennen_art:
                  type: string
                  enum: ["downhill", "freeride", "rennen", "road", "mtb", ""]
                  default: ""
                  description: Race type. Empty string ("") indicates no race type specified. Use 'downhill' for high-risk routes.
                  example: "road"
                geschlecht:
                  type: string
                  enum: ["m", "mann", "male", "w", "frau", "female", ""]
                  default: ""
                  description: Rider gender. Empty string ("") indicates no gender specified.
                  example: "w"
                alter:
                  type: integer
                  minimum: 0
                  default: 42
                  description: Rider age. Older age may influence risk of injuries like back pain.
                  example: 42
                material:
                  type: string
                  enum: ["carbon", "aluminium", "steel"]
                  default: "aluminium"
                  description: Bicycle material. 'carbon' may reduce fatigue but increase crash damage risk.
                  example: "aluminium"
                schutzausruestung:
                  type: object
                  properties:
                    helm:
                      type: boolean
                      default: false
                    protektoren:
                      type: boolean
                      default: false
                  description: Rider protective equipment. Setting 'helm' to true reduces head injury risk.
                  example: {"helm": true, "protektoren": false}
                overuse_knee:
                  type: boolean
                  default: false
                  description: Indicates knee overuse issues. Set to true for riders with known knee problems.
                  example: false
                rueckenschmerzen:
                  type: boolean
                  default: false
                  description: Indicates back pain. Set to true for riders with back issues to adjust risk.
                  example: false
                massenstart:
                  type: boolean
                  default: false
                  description: Indicates a mass start. Set to true for races with many riders starting together.
                  example: false
                wetter_override:
                  $ref: '#/components/schemas/Weather'
                  description: Optional weather data to override API fetch. Use if real-time weather data is unavailable.
      responses:
        '200':
          description: Heatmap URL, distance, segment info, and detailed report.
          content:
            application/json:
              schema:
                type: object
                required:
                  - heatmap_url
                  - distance_km
                  - segments
                  - detailed_report
                properties:
                  heatmap_url:
                    type: string
                    description: URL to the generated heatmap.
                    example: "https://gpx-heatmap-api.onrender.com/static/heatmap_20250409120000.html"
                  distance_km:
                    type: number
                    description: Total route length in kilometers.
                    example: 10.5
                  segments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Segment'
                    description: Route segment details.
                  detailed_report:
                    type: string
                    description: Detailed report with route analysis, including route length, weather conditions, risk assessment, likely injuries, prevention recommendations, sources, and interactive map details.
                    example: |
                      Route Length: The route covers 10.5 km.
                      Weather Conditions: Representative Point: (Lat: 48.137, Lon: 11.576)\nDate and Time: 2025-04-09T07:00:00Z\nTemperature: 15°C, Wind: 10 km/h, Precipitation: 0 mm, Condition: klar\nSource: WeatherStack
                      Risk Assessment per Segment: Segment 1: Risk: 2 (Slope: 1.0%, Terrain: Flach, Surface: asphalt)\nSegment 2: Risk: 3 (Slope: 5.0%, Terrain: Anstieg, sharp curve) – 🚑 Sanitäter recommended
                      Overall Risk: Average Risk Score: 2.5 (elevated)
                      Likely Injuries: Typical Injuries: Abschürfungen, Prellungen, Claviculafraktur\nRecommended Studies: (Rehlinghaus 2022), (Nelson 2010)
                      Prevention Recommendations: watch for sharp curves, ride cautiously on steep slopes
                      Sources: Scientific Sources: (Rehlinghaus 2022), (Kronisch 2002, p. 5), (Nelson 2010), (Dannenberg 1996), (Ruedl 2015), (Clarsen 2005)\nWeather Data: WeatherStack
                      Interactive Map Details: Heatmap URL: https://gpx-heatmap-api.onrender.com/static/heatmap_20250409120000.html\nColor Scale: green = low risk, orange = medium risk, red = high risk.\n🚑 markers indicate segments where a paramedic is recommended.
        '400':
          description: Invalid input data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid coordinates received"
        '413':
          description: Request exceeds track point limit.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Too many track points: 150000. Maximum allowed: 100,000"
        '429':
          description: Rate limit exceeded (10/min per endpoint, 200/day, 50/hour globally).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Too many requests: please try again later"
        '500':
          description: Server error during processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Map creation failed"

  /parse-gpx:
    post:
      tags: [GPX]
      summary: Parse GPX File and Extract Coordinates
      description: |
        Extracts track or route points from a Base64-encoded GPX file.
        Limited to 100,000 track points.
        Only Base64 input is supported for GPT Actions to ensure JSON compatibility.
      operationId: parseGpxFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_base64:
                  type: string
                  description: Base64-encoded GPX file. Only this format is supported for GPT Actions.
                  example: "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48Z3B4Pjx0cms+PHRya3NlZz48dHJrcHQgbGF0PSI0OC4xMzcxNTQiIGxvbj0iMTEuNTc2MTI0Ij48ZWxlPjUyMDwvZWxlPjwvdHJrcHQ+PC90cmtzZWc+PC90cmsgPC9ncHg+"
              required:
                - file_base64
      responses:
        '200':
          description: Extracted coordinates and distance.
          content:
            application/json:
              schema:
                type: object
                required:
                  - coordinates
                  - distance_km
                properties:
                  coordinates:
                    type: array
                    items:
                      $ref: '#/components/schemas/Coordinate'
                    description: Array of [latitude, longitude, elevation?] coordinates.
                    example: [[48.137154, 11.576124, 520], [48.138, 11.577, 521], [48.139, 11.578, 522]]
                  distance_km:
                    type: number
                    description: Total route length in kilometers.
                    example: 10.5
        '400':
          description: Invalid GPX file or input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid GPX file: malformed XML"
        '413':
          description: Exceeds track point limit.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Too many track points: 150,000. Maximum allowed: 100,000"
        '429':
          description: Rate limit exceeded (10/min per endpoint, 200/day, 50/hour globally).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Too many requests: please try again later"
        '500':
          description: Server error during processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Error processing GPX data"

  /chunk-upload:
    post:
      tags: [Utility]
      summary: Split Coordinates into Chunks and Store
      description: |
        Splits coordinates into chunks (default size: 200 points) and stores them in a SQLite database.
        Returns a list of chunk filenames.
        Useful for processing large routes in smaller parts.
      operationId: chunkUpload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - coordinates
              properties:
                coordinates:
                  type: array
                  items:
                    $ref: '#/components/schemas/Coordinate'
                  description: Array of [latitude, longitude, elevation?] coordinates.
                  example: [[48.137154, 11.576124, 520], [48.138, 11.577, 521], [48.139, 11.578, 522]]
                chunk_size:
                  type: integer
                  minimum: 1
                  default: 200
                  description: Number of coordinates per chunk.
                  example: 200
      responses:
        '200':
          description: Confirmation of stored chunks.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - chunks
                properties:
                  message:
                    type: string
                    description: Confirmation message.
                    example: "3 chunks stored"
                  chunks:
                    type: array
                    items:
                      type: string
                    description: List of chunk filenames.
                    example: ["chunk_1.json", "chunk_2.json", "chunk_3.json"]
        '400':
          description: Invalid coordinates.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid coordinates received"
        '413':
          description: Request exceeds track point limit.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Too many track points: 150,000. Maximum allowed: 100,000"
        '429':
          description: Rate limit exceeded (10/min per endpoint, 200/day, 50/hour globally).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Too many requests: please try again later"
        '500':
          description: Server error during storage.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Error saving chunks"

components:
  schemas:
    Coordinate:
      type: array
      minItems: 2
      maxItems: 3
      items:
        type: number
      description: Coordinate in format [latitude, longitude, elevation?]. Latitude (-90 to 90), Longitude (-180 to 180), Elevation (optional).
      example: [48.137154, 11.576124, 520]

    Weather:
      type: object
      properties:
        temperature:
          type: number
          description: Temperature in °C.
          example: 15
        wind_speed:
          type: number
          description: Wind speed in km/h.
          example: 10
        precip:
          type: number
          description: Precipitation in mm.
          example: 0
        condition:
          type: string
          description: Weather condition description.
          example: "klar"
      required:
        - temperature
        - wind_speed
        - precip
        - condition
      description: Weather data for a specific point.

    Segment:
      type: object
      properties:
        segment_index:
          type: integer
          description: Index of the segment.
          example: 1
        center:
          type: object
          properties:
            lat:
              type: number
              description: Latitude of segment center.
              example: 48.137154
            lon:
              type: number
              description: Longitude of segment center.
              example: 11.576124
          required:
            - lat
            - lon
        slope:
          type: number
          description: Slope in percent.
          example: 1.0
        sharp_curve:
          type: boolean
          description: Indicates a sharp curve (≥60°).
          example: false
        terrain:
          type: string
          enum: ["Anstieg", "Abfahrt", "Flach"]
          description: Terrain type based on slope.
          example: "Flach"
        weather:
          $ref: '#/components/schemas/Weather'
        nighttime:
          type: boolean
          description: Indicates nighttime at segment location.
          example: false
        street_surface:
          type: string
          enum: ["asphalt", "cobblestone", "gravel"]
          description: Street surface type.
          example: "asphalt"
        risk:
          type: integer
          minimum: 1
          maximum: 5
          description: Risk score (1 = low, 5 = critical).
          example: 2
        injuries:
          type: array
          items:
            type: string
          description: Typical injuries for the segment's risk level.
          example: ["Abschürfungen", "Prellungen"]
        sani_needed:
          type: boolean
          description: Indicates if a paramedic is recommended.
          example: false
      required:
        - segment_index
        - center
        - slope
        - sharp_curve
        - terrain
        - weather
        - nighttime
        - street_surface
        - risk
        - injuries
        - sani_needed
      description: Details of a route segment.

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message.
      required:
        - error
      description: Standard error response.
      example:
        error: "Invalid coordinates received"
