openapi: 3.0.0
info:
  title: CycleDoc GPX Heatmap API
  version: "1.0"
  description: |
    Diese API verarbeitet GPX-Daten und erstellt Risiko-Heatmaps auf Basis von Wetter, Streckenprofil und wissenschaftlicher Studienlage.
    Sie unterstützt das Parsen von GPX-Dateien, Segmentierung großer Strecken und die automatische Analyse via Wetterdaten oder manuelle Eingabe.

servers:
  - url: https://gpx-heatmap-api.onrender.com

paths:
  /parse-gpx:
    post:
      summary: GPX-Datei parsen
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Extrahierte Koordinaten aus der Datei
          content:
            application/json:
              schema:
                type: object
                properties:
                  coordinates:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
        '400':
          description: Keine Datei empfangen

  /chunk-upload:
    post:
      summary: GPX-Koordinaten in Chunks speichern (serverseitig)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coordinates:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
                chunk_size:
                  type: integer
                  default: 200
      responses:
        '200':
          description: Anzahl der gespeicherten Chunks
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  chunks:
                    type: array
                    items:
                      type: string

  /heatmap-with-weather:
    post:
      summary: Risikoanalyse & Heatmap generieren
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coordinates:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
                fahrer_typ:
                  type: string
                  example: hobby
                anzahl:
                  type: integer
                  example: 2
                rennen_art:
                  type: string
                  example: tour
                geschlecht:
                  type: string
                  example: mixed
                alter:
                  type: integer
                  example: 65
                material:
                  type: string
                  example: aluminium
                massenstart:
                  type: boolean
                  example: false
                overuse_knee:
                  type: boolean
                  example: false
                rueckenschmerzen:
                  type: boolean
                  example: false
                start_time:
                  type: string
                  format: date-time
                  example: "2025-04-11T12:00:00Z"
                wetter_override:
                  type: object
                  example:
                    temperature: 15
                    wind_speed: 10
                    precip: 0
                    condition: Klar
                schutzausruestung:
                  type: object
                  properties:
                    helm:
                      type: boolean
                    protektoren:
                      type: boolean
      responses:
        '200':
          description: Analyse mit Heatmap-Link und Risikosegmenten
          content:
            application/json:
              schema:
                type: object
                properties:
                  heatmap_url:
                    type: string
                  segments:
                    type: array
                    items:
                      type: object
                      properties:
                        segment_index:
                          type: integer
                        center:
                          type: object
                          properties:
                            lat:
                              type: number
                            lon:
                              type: number
                        slope:
                          type: number
                        sharp_curve:
                          type: boolean
                        terrain:
                          type: string
                        weather:
                          type: object
                        street_surface:
                          type: string
                        nighttime:
                          type: boolean
                        risk:
                          type: integer
                        injuries:
                          type: array
                          items:
                            type: string
                        sani_needed:
                          type: boolean
        '400':
          description: Fehlerhafte oder fehlende Daten
