openapi: 3.0.3
info:
  title: CycleDoc GPX Heatmap API
  version: "1.0"
  description: >
    Diese API verarbeitet GPX-Daten und erstellt Risiko-Heatmaps auf Basis von Wetter, Streckenprofil und wissenschaftlicher Studienlage.
    Unterstützt: Datei-Upload, Chunking, Segmentanalyse, Heatmap mit Risikobewertung und Streckenlänge.

servers:
  - url: https://gpx-heatmap-api.onrender.com

paths:
  /parse-gpx:
    post:
      summary: GPX-Datei hochladen und in Koordinaten umwandeln
      operationId: parseGpx
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Koordinaten erfolgreich extrahiert
          content:
            application/json:
              schema:
                type: object
                properties:
                  coordinates:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
                  distance_km:
                    type: number
                    description: Gesamtlänge der Tour in Kilometern
        '400':
          description: Keine Datei empfangen

  /chunk-upload:
    post:
      summary: Zerlege viele Koordinaten in serverseitige Chunks
      operationId: chunkUpload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coordinates:
                  type: array
                  items:
                    type: array
                    items: { type: number }
                chunk_size:
                  type: integer
                  default: 200
      responses:
        '200':
          description: Chunks gespeichert
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  chunks:
                    type: array
                    items: { type: string }

  /heatmap-with-weather:
    post:
      summary: Standard-Risikoanalyse mit 0.2 km Segmenten
      operationId: generateHeatmap
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeatmapRequest'
      responses:
        '200':
          description: Heatmap mit Risikoanalyse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeatmapResponse'

  /heatmap-quick:
    post:
      summary: Präzise Risikoanalyse (SpeedBoost, 0.005 km)
      operationId: generateHeatmapQuick
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeatmapRequest'
      responses:
        '200':
          description: Risikoanalyse mit Heatmap und Streckenlänge
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeatmapResponse'

components:
  schemas:

    HeatmapRequest:
      type: object
      properties:
        coordinates:
          type: array
          items:
            type: array
            items: { type: number }
        fahrer_typ:
          type: string
          example: hobby
        anzahl:
          type: integer
          example: 2
        alter:
          type: integer
        geschlecht:
          type: string
          example: mixed
        massenstart:
          type: boolean
        overuse_knee:
          type: boolean
        rueckenschmerzen:
          type: boolean
        material:
          type: string
          example: aluminium
        rennen_art:
          type: string
          example: road
        schutzausruestung:
          type: object
          properties:
            helm: { type: boolean }
            protektoren: { type: boolean }
        wetter_override:
          type: object
          properties:
            temperature: { type: number }
            wind_speed: { type: number }
            precip: { type: number }
            condition: { type: string }
        start_time:
          type: string
          format: date-time

    HeatmapResponse:
      type: object
      properties:
        heatmap_url:
          type: string
          format: uri
        distance_km:
          type: number
          description: Gesamtlänge der Strecke in Kilometern
        segments:
          type: array
          items:
            $ref: '#/components/schemas/Segment'

    Segment:
      type: object
      properties:
        segment_index: { type: integer }
        center:
          type: object
          properties:
            lat: { type: number }
            lon: { type: number }
        slope: { type: number }
        sharp_curve: { type: boolean }
        terrain: { type: string }
        street_surface: { type: string }
        nighttime: { type: boolean }
        risk:
          type: integer
          minimum: 1
          maximum: 5
        injuries:
          type: array
          items: { type: string }
        sani_needed: { type: boolean }
        weather:
          type: object
          properties:
            temperature: { type: number }
            wind_speed: { type: number }
            precip: { type: number }
            condition: { type: string }
