openapi: 3.1.0
info:
  title: CycleDoc Heatmap API
  version: "1.0"
  description: >
    Diese API analysiert GPX-Daten, segmentiert die Strecke, berechnet Risiken auf Basis von Wetter, Kurven, Oberfläche etc.,
    erstellt interaktive Karten mit Farbvisualisierung und Sanitäter-Logik und liefert Ergebnisse als strukturierte JSON-Risikoanalyse.

servers:
  - url: https://gpx-heatmap-api.onrender.com

paths:
  /heatmap-quick:
    post:
      summary: Segmentierte Risikoanalyse & Heatmap-Visualisierung (SpeedBoost)
      operationId: analyzeHeatmapQuick
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeatmapRequest'
      responses:
        '200':
          description: Risikoanalyse erfolgreich abgeschlossen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeatmapResponse'
        '400':
          description: Ungültige oder fehlende Koordinaten
        '500':
          description: Interner Serverfehler

  /parse-gpx:
    post:
      summary: GPX-Datei hochladen und Koordinaten + Distanz extrahieren
      operationId: parseGpxFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: GPX-Daten erfolgreich geparst
          content:
            application/json:
              schema:
                type: object
                properties:
                  coordinates:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
                  distance_km:
                    type: number
        '400':
          description: Fehlerhafte oder ungültige GPX-Datei

  /chunk-upload:
    post:
      summary: GPX-Koordinaten in Chunks unterteilen und speichern
      operationId: chunkUpload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coordinates:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
                chunk_size:
                  type: integer
                  default: 200
      responses:
        '200':
          description: Chunks erfolgreich gespeichert
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  chunks:
                    type: array
                    items:
                      type: string
        '400':
          description: Keine gültigen Koordinaten empfangen

  /openapi.yaml:
    get:
      summary: Liefert die OpenAPI-Spezifikation (YAML)
      operationId: getOpenapiYaml
      responses:
        '200':
          description: YAML-Datei gefunden
          content:
            text/yaml:
              schema:
                type: string
        '404':
          description: Datei nicht gefunden

components:
  schemas:
    HeatmapRequest:
      type: object
      properties:
        coordinates:
          type: array
          items:
            type: array
            items:
              type: number
        fahrer_typ:
          type: string
        anzahl:
          type: integer
        alter:
          type: integer
        geschlecht:
          type: string
        massenstart:
          type: boolean
        overuse_knee:
          type: boolean
        rueckenschmerzen:
          type: boolean
        material:
          type: string
        rennen_art:
          type: string
        start_time:
          type: string
          format: date-time
        wetter_override:
          type: object
          properties:
            temperature:
              type: number
            wind_speed:
              type: number
            precip:
              type: number
            condition:
              type: string
        schutzausruestung:
          type: object
          properties:
            helm:
              type: boolean
            protektoren:
              type: boolean

    HeatmapResponse:
      type: object
      properties:
        heatmap_url:
          type: string
          format: uri
        distance_km:
          type: number
        segments:
          type: array
          items:
            type: object
            properties:
              segment_index:
                type: integer
              center:
                type: object
                properties:
                  lat:
                    type: number
                  lon:
                    type: number
              slope:
                type: number
              sharp_curve:
                type: boolean
              terrain:
                type: string
              weather:
                type: object
                properties:
                  temperature: { type: number }
                  wind_speed: { type: number }
                  precip: { type: number }
                  condition: { type: string }
              street_surface:
                type: string
              nighttime:
                type: boolean
              risk:
                type: integer
              injuries:
                type: array
                items: { type: string }
              sani_needed:
                type: boolean
