# render.yaml

services:
  - type: web
    name: cycledoc-api
    env: python3
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: WEATHERSTACK_API_KEY
        value: "<YOUR_WEATHERSTACK_API_KEY>"
    healthCheckPath: "/"
    regions:
      - oregon
      - frankfurt

# Optional: Datenbank-Service
  - type: postgres
    name: cycledoc-db
    plan: free
    postgresVersion: "14"
    envVars:
      - key: DATABASE_URL
        fromService: cycledoc-db

# Redis für Celery
  - type: redis
    name: cycledoc-redis
    plan: free
