# render.yaml
services:
  - type: web
    name: gpx-heatmap-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    staticPublishPath: static
startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
