services:
  - type: web
    name: gpx-heatmap-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: WEATHERSTACK_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-gpx-heatmap
          property: connectionString
    regions:
      - frankfurt
    plan: standard
    autoDeploy: true

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A main.celery_app worker --loglevel=info
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-gpx-heatmap
          property: connectionString
    regions:
      - frankfurt
    plan: standard
    autoDeploy: true

  - type: redis
    name: redis-gpx-heatmap
    ipAllowList: []
    regions:
      - frankfurt
    plan: free
    maxmemoryPolicy: allkeys-lru
